import { PLANET_CONFIG, type PlanetConfig } from './config';

export type VariantName = PlanetConfig['variant'];

/** Three directions for review. Each overrides keys of PLANET_CONFIG. */
export const VARIANTS: Record<VariantName, Partial<PlanetConfig>> = {
  /** A — precise monochrome halftone. Editorial and restrained. */
  ledger: {
    pointLayout: 'grid',
    pointCountDesktop: 11000,
    pointCountMobile: 5000,
    useLandMask: false,
    sizeByLight: true,
    sizeMinPx: 0.9,
    sizeMaxPx: 3.6,
    colorPlanet: '#5B636B',
    lightDirection: [-0.6, 0.55, 0.6],
    landOpacity: 0.92,
    silhouettePower: 0.55,
    lightenAmount: 0,
    glow: false,
    outline: true,
    outlineColor: '#7C858D',
    outlineOpacity: 0.32,
    shadow: true,
    shadowOpacity: 0.14,
    ringRadii: [1.32, 1.48],
    ringInclinationsDeg: [22, 78],
    ringAzimuthsDeg: [0, 80],
    ringRollsDeg: [-14, 36],
    colorRing: '#111214',
    ringOpacity: 0.22,
    ringBackFade: 0.15,
    nodePeriodsSec: [18, 26],
    nodeTrailLength: 0,
    badgeSize: 0.14,
  },

  /** B — solid ink→indigo sphere with a glass rim; land in light dots. Bold product-render weight. */
  core: {
    pointCountDesktop: 12000,
    pointCountMobile: 5000,
    useLandMask: true,
    landCoverage: 0.32,
    colorPlanet: '#FFFFFF',
    colorOcean: '#B7B9FF',
    landOpacity: 0.85,
    oceanOpacity: 0.16,
    landPointSizePx: 2.4,
    oceanPointSizePx: 1.4,
    silhouettePower: 0.7,
    lightenAmount: 0,
    shell: true,
    shellColorDark: '#0B0C26',
    shellColorLight: '#4B4BF7',
    shellColorRim: '#A5A5FF',
    shellSpecular: 0.4,
    glow: true,
    glowOpacity: 0.16,
    glowScale: 3.4,
    shadow: true,
    shadowOpacity: 0.22,
    shadowWidth: 2.2,
    ringRadii: [1.3, 1.42],
    ringInclinationsDeg: [16, 72],
    ringAzimuthsDeg: [6, 84],
    ringRollsDeg: [-10, 32],
    colorRing: '#111214',
    ringOpacity: 0.3,
    ringBackFade: 0.1,
    nodePeriodsSec: [18, 24],
    nodeTrailLength: 4,
    nodeTrailOpacity: 0.3,
    badgeSize: 0.14,
  },

  /** C — light wire lattice with elevated payment arcs and indigo pulses. */
  network: {
    pointLayout: 'fibonacci',
    pointCountDesktop: 2200,
    pointCountMobile: 1200,
    useLandMask: false,
    colorPlanet: '#7C858D',
    landOpacity: 0.75,
    landPointSizePx: 2.3,
    silhouettePower: 0.6,
    lightenAmount: 0,
    lattice: true,
    latticeStepDeg: 15,
    latticeColor: '#7C858D',
    latticeOpacity: 0.3,
    arcs: true,
    arcCount: 10,
    arcLift: 0.26,
    arcOpacity: 0.4,
    arcPulseLength: 0.2,
    arcPulsePeriodSec: 4,
    arcPulseColor: '#4B4BF7',
    glow: false,
    outline: true,
    outlineOpacity: 0.28,
    shadow: true,
    shadowOpacity: 0.12,
    ringRadii: [1.4],
    ringInclinationsDeg: [20],
    ringAzimuthsDeg: [0],
    ringRollsDeg: [-16],
    colorRing: '#7C858D',
    ringOpacity: 0.3,
    ringBackFade: 0.2,
    nodePeriodsSec: [22],
    nodeTrailLength: 0,
    badgeSize: 0.14,
  },
};

export function resolveConfig(variant?: string | null): PlanetConfig {
  const name = (variant && variant in VARIANTS ? variant : PLANET_CONFIG.variant) as VariantName;
  return { ...PLANET_CONFIG, ...VARIANTS[name], variant: name };
}
