import { PLANET_CONFIG, type PlanetConfig } from './config';

export type VariantName = PlanetConfig['variant'];

/** Three directions for review. Each overrides keys of PLANET_CONFIG. */
/** The client's reference look: mid-grey dotted globe, tight hairline orbits, coin tokens in transit. */
const ORBITAL: Partial<PlanetConfig> = {
  pointLayout: 'grid',
  pointCountDesktop: 9000,
  pointCountMobile: 4200,
  useLandMask: false,
  sizeByLight: true,
  sizeMinPx: 1.5,
  sizeMaxPx: 3.1,
  colorPlanet: '#7C858D',
  landOpacity: 0.9,
  silhouettePower: 0.4,
  lightenAmount: 0,
  lightDirection: [-0.5, 0.7, 0.55],
  glow: false,
  outline: false,
  shadow: true,
  shadowOpacity: 0.1,
  shadowWidth: 2.3,
  shadowOffsetY: -1.22,
  ringRadii: [1.14, 1.27],
  ringInclinationsDeg: [18, 64],
  ringAzimuthsDeg: [0, 46],
  ringRollsDeg: [-12, 22],
  colorRing: '#B5BAC0',
  ringOpacity: 0.75,
  ringBackFade: 0.25,
  ringTubeRadius: 0.0024,
  nodePeriodsSec: [20, 27],
  nodeTrailLength: 0,
  badgeSize: 0.18,
  badgeTexturePx: 256,
  rotationPeriodSec: 80,
  planetCenterX: 0.7,
  planetCenterY: 0.5,
  sphereDiameterFraction: 0.64,
  tabletPlanetCenterX: 0.7,
  tabletSphereDiameterFraction: 0.54,
};

/** Shared by the three switcher globes: real geography, no orbit lines, coins in transit. */
const ATLAS: Partial<PlanetConfig> = {
  ...ORBITAL,
  ringsVisible: false,
  coinMode: 'popup',
  assemble: true,
  ringRadii: [1.18, 1.34],
  ringInclinationsDeg: [22, 58],
  ringAzimuthsDeg: [0, 40],
  ringRollsDeg: [-14, 18],
  nodePeriodsSec: [26, 34],
  badgeSize: 0.19,
  badgeTexturePx: 256,
  useLandMask: true,
  landMaskSource: 'image',
  coastSoftness: 0.22,
  pointLayout: 'grid',
  pointCountDesktop: 16000,
  pointCountMobile: 5600,
  sizeByLight: false,
  litInfluence: 0.55,
  landPointSizePx: 2.9,
  oceanPointSizePx: 1.2,
  colorPlanet: '#67707A',
  colorOcean: '#B4BAC1',
  landOpacity: 0.96,
  oceanOpacity: 0.55,
  silhouettePower: 0.45,
  body: true,
  bodyColor: '#E1E4E8',
  bodyOpacity: 1,
  bodyEdge: 0.9,
  shadow: false,
  halo: true,
  rotationPeriodSec: 110,
  staticRotationDeg: -70,
};

/** The three globe treatments offered by the in-page switcher. */
export const GLOBES: { id: 'globe-halftone' | 'globe-atlas' | 'globe-matte'; label: string; blurb: string }[] = [
  { id: 'globe-halftone', label: 'Halftone', blurb: 'Continents as a light-shaded halftone' },
  { id: 'globe-atlas', label: 'Atlas', blurb: 'Real continents in dots on a soft grey body' },
  { id: 'globe-matte', label: 'Matte', blurb: 'Solid shaded sphere with continents in white dots' },
];

export const VARIANTS: Record<VariantName, Partial<PlanetConfig>> = {
  'globe-atlas': ATLAS,
  /** Same geography, rendered as a pure halftone: no body disc, dots carry all the shading. */
  'globe-halftone': {
    ...ATLAS,
    body: false,
    litInfluence: 0.85,
    landPointSizePx: 3.1,
    oceanPointSizePx: 1.2,
    colorPlanet: '#5F676F',
    colorOcean: '#AEB4BA',
    oceanOpacity: 0.5,
  },
  /** Solid matte grey sphere with the continents picked out in white dots. */
  'globe-matte': {
    ...ATLAS,
    body: false,
    shell: true,
    shellColorDark: '#5F676F',
    shellColorLight: '#AEB4BA',
    shellColorRim: '#D6D9DD',
    shellSpecular: 0.22,
    litInfluence: 0.2,
    pointCountDesktop: 12000,
    landPointSizePx: 2.2,
    oceanPointSizePx: 0.9,
    colorPlanet: '#FFFFFF',
    colorOcean: '#FFFFFF',
    landOpacity: 0.92,
    oceanOpacity: 0.28,
    silhouettePower: 0.9,
  },
  orbital: ORBITAL,
  /** Centred, low and large: the bottom of the globe is cut by the hero edge. */
  'orbital-rise': {
    ...ORBITAL,
    planetCenterX: 0.5,
    planetCenterY: 1.08,
    sphereDiameterFraction: 1.0,
    pointCountDesktop: 15000,
    sizeMinPx: 1.1,
    sizeMaxPx: 2.3,
    shadow: false,
    ringRadii: [1.1, 1.2],
    ringInclinationsDeg: [16, 42],
    ringAzimuthsDeg: [0, 50],
    ringRollsDeg: [-4, 10],
    badgeSize: 0.11,
    nodePeriodsSec: [24, 32],
    mobilePlanetCenterX: 0.5,
    mobileSphereDiameterFraction: 1.2,
  },
  /** Inside the product panel: the panel is the host, so the globe is centred in it. */
  'orbital-stage': {
    ...ORBITAL,
    captureSphereDiameterFraction: 0.68,
    badgeSize: 0.16,
    shadowOpacity: 0.08,
  },
  /** A — precise monochrome halftone. Editorial and restrained. */
  ledger: {
    pointLayout: 'grid',
    pointCountDesktop: 11000,
    pointCountMobile: 5000,
    useLandMask: false,
    sizeByLight: true,
    sizeMinPx: 0.9,
    sizeMaxPx: 3.6,
    colorPlanet: '#5B636B',
    lightDirection: [-0.6, 0.55, 0.6],
    landOpacity: 0.92,
    silhouettePower: 0.55,
    lightenAmount: 0,
    glow: false,
    outline: true,
    outlineColor: '#7C858D',
    outlineOpacity: 0.32,
    shadow: true,
    shadowOpacity: 0.14,
    ringRadii: [1.32, 1.48],
    ringInclinationsDeg: [22, 78],
    ringAzimuthsDeg: [0, 80],
    ringRollsDeg: [-14, 36],
    colorRing: '#111214',
    ringOpacity: 0.22,
    ringBackFade: 0.15,
    nodePeriodsSec: [18, 26],
    nodeTrailLength: 0,
    badgeSize: 0.14,
  },

  /** B — solid ink→indigo sphere with a glass rim; land in light dots. Bold product-render weight. */
  core: {
    pointCountDesktop: 12000,
    pointCountMobile: 5000,
    useLandMask: true,
    landCoverage: 0.32,
    colorPlanet: '#FFFFFF',
    colorOcean: '#B7B9FF',
    landOpacity: 0.85,
    oceanOpacity: 0.16,
    landPointSizePx: 2.4,
    oceanPointSizePx: 1.4,
    silhouettePower: 0.7,
    lightenAmount: 0,
    shell: true,
    shellColorDark: '#0B0C26',
    shellColorLight: '#4B4BF7',
    shellColorRim: '#A5A5FF',
    shellSpecular: 0.4,
    glow: true,
    glowOpacity: 0.16,
    glowScale: 3.4,
    shadow: true,
    shadowOpacity: 0.22,
    shadowWidth: 2.2,
    ringRadii: [1.3, 1.42],
    ringInclinationsDeg: [16, 72],
    ringAzimuthsDeg: [6, 84],
    ringRollsDeg: [-10, 32],
    colorRing: '#111214',
    ringOpacity: 0.3,
    ringBackFade: 0.1,
    nodePeriodsSec: [18, 24],
    nodeTrailLength: 4,
    nodeTrailOpacity: 0.3,
    badgeSize: 0.14,
  },

  /** C — light wire lattice with elevated payment arcs and indigo pulses. */
  network: {
    pointLayout: 'fibonacci',
    pointCountDesktop: 2200,
    pointCountMobile: 1200,
    useLandMask: false,
    colorPlanet: '#7C858D',
    landOpacity: 0.75,
    landPointSizePx: 2.3,
    silhouettePower: 0.6,
    lightenAmount: 0,
    lattice: true,
    latticeStepDeg: 15,
    latticeColor: '#7C858D',
    latticeOpacity: 0.3,
    arcs: true,
    arcCount: 10,
    arcLift: 0.26,
    arcOpacity: 0.4,
    arcPulseLength: 0.2,
    arcPulsePeriodSec: 4,
    arcPulseColor: '#4B4BF7',
    glow: false,
    outline: true,
    outlineOpacity: 0.28,
    shadow: true,
    shadowOpacity: 0.12,
    ringRadii: [1.4],
    ringInclinationsDeg: [20],
    ringAzimuthsDeg: [0],
    ringRollsDeg: [-16],
    colorRing: '#7C858D',
    ringOpacity: 0.3,
    ringBackFade: 0.2,
    nodePeriodsSec: [22],
    nodeTrailLength: 0,
    badgeSize: 0.14,
  },
};

export function resolveConfig(variant?: string | null): PlanetConfig {
  const name = (variant && variant in VARIANTS ? variant : PLANET_CONFIG.variant) as VariantName;
  return { ...PLANET_CONFIG, ...VARIANTS[name], variant: name };
}
