import { chromium } from 'playwright-core';
const b = await chromium.launch({ executablePath:'/opt/pw-browsers/chromium', args:['--no-sandbox','--use-gl=swiftshader']});
const p = await b.newPage({viewport:{width:1600,height:1000}});
await p.goto('http://localhost:5173/', {waitUntil:'networkidle'});
await p.evaluate(()=>document.fonts.ready);
await p.waitForTimeout(1200);
const a = p.locator('.bcard--onboard').first();
await a.scrollIntoViewIfNeeded(); await p.waitForTimeout(400);
await a.screenshot({path:'/tmp/real-onboard.png'});
const c = p.locator('.bcard--bonus').first();
await c.scrollIntoViewIfNeeded(); await p.waitForTimeout(400);
await c.screenshot({path:'/tmp/real-bonus.png'});
await b.close();
